### ISSUE TITLE
DMS commands not working with otcextensions 0.31.0 anymore

### ISSUE THREAD

**Issue by danielaebert** [opentelekomcloud/python-otcextensions#413]
With the latest otcextensions (version 0.31.0) the DMS commands do not work anymore.

Before:

$ pip list |grep otcextensions
otcextensions          0.30.9
$ ~/git/apimon-tests/playbooks$ openstack dms az list
+----------------------------------+----------+----------+------+-------------------------+
| ID                               | name     | code     | port | has_available_resources |
+----------------------------------+----------+----------+------+-------------------------+
| bf84aba586ce4e948da0b97d9a7d62fb | eu-de-01 | eu-de-01 | 8002 | True                    |
| bf84aba586ce4e948da0b97d9a7d62fc | eu-de-02 | eu-de-02 | 8003 | True                    |
| eu-de-03                         | eu-de-03 | eu-de-03 | 8027 | True                    |
+----------------------------------+----------+----------+------+-------------------------+

Now:

$ pip list |grep otcextensions
otcextensions          0.31.0
$ ~/git/apimon-tests/playbooks$ openstack dms az list
'NoneType' object has no attribute 'api_version'

**Comment by danielaebert** [comment]
Issue seems to be fixed in version 0.31.2

$ pip list |grep otc
otcextensions          0.31.2
$ openstack dms az list
+----------------------------------+----------+----------+------+-------------------------+
| ID                               | name     | code     | port | has_available_resources |
+----------------------------------+----------+----------+------+-------------------------+
| bf84aba586ce4e948da0b97d9a7d62fb | eu-de-01 | eu-de-01 | 8002 | True                    |
| bf84aba586ce4e948da0b97d9a7d62fc | eu-de-02 | eu-de-02 | 8003 | True                    |
| eu-de-03                         | eu-de-03 | eu-de-03 | 8027 | True                    |
+----------------------------------+----------+----------+------+-------------------------+

Issue can be closed
